version: '3.8'

services:
  fastapi-app:
    build:
      context: ./fastapi-backend
      dockerfile: fastapi.dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
      ]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./flask-app/:/app/
