providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: false

http:
  routers:
    fastapi-router:
      rule: "Host(`fastapi.localhost`)"
      entryPoints:
        - web
      service: fastapi-backend

    express-router:
      rule: "Host(`express.localhost`)"
      entryPoints:
        - web
      service: express-api

    flask-router:
      rule: "Host(`flask.localhost`)"
      entryPoints:
        - web
      service: flask-app

    jupyterlab-router:
      rule: "Host(`jupyterlab.localhost`)"
      entryPoints:
        - web
      service: jupyterlab

    # react-vite-router:
    #   rule: "Host(`react-vite.localhost`)"
    #   entryPoints:
    #     - web
    #   service: react-vite
      
    dashboard:
      rule: Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - auth

  middlewares:
    auth:
      basicAuth:
        users:
          - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" #username: test || password: test
          - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0" #username: test2 || password: test2

          # https://dev.to/limal/basic-http-authentication-in-traefik-15l6

  services:
    fastapi-backend:
      loadBalancer:
        servers:
          - url: http://fastapi-backend:8000
    express-api:
      loadBalancer:
        servers:
          - url: http://express-api:3000
    flask-app:
      loadBalancer:
        servers:
          - url: http://flask-app:5000
    jupyterlab:
      loadBalancer:
        servers:
          - url: http://jupyterlab:8888
    # react-vite:
    #   loadBalancer:
    #     servers:
    #       - url: http://react-vite:5173
# log:
#   level: DEBUG
#   filePath: "/logs/log-file.log"
#   format: json

# accessLog:
#   filePath: "/logs/access.log"
#   bufferingSize: 100
#   format: json
#   fields:
#     defaultMode: keep
#     names:
#       StartUTC: keep
#       StartLocal: keep
#     headers:
#       defaultMode: keep
#       names:
#         User-Agent: keep
#         Authorization: keep
#         Content-Type: keep
#         RequestAddr: keep
#         RequestHost: keep
#         RequestPort: keep
#         RequestMethod: keep
#         RequestPath: keep
#         RequestProtocol: keep
#         RequestScheme: keep
